post/urls.py
from django.urls import path 
from .views import * 

app_name = 'post' 

urlpatterns = [
    path('', all, name='all'),
    path('<int:id>/', single_post, name='single-post'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls', namespace="posts")),
]

author/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=150) 
    email = models.EmailField(max_length=255, unique=True) 

    def __str__(self):
        return self.name 

post/models.py
from django.db import models
from django.utils.text import slugify

from author.models import Author

# Create your models here.



class Post(models.Model):
    POST_TYPE_CHOICES = (
        ('question', 'سؤال'),
        ('post', 'منشور'),
        ('article', 'مقالة'),
    )

    author = models.OneToOneField(Author, on_delete=models.CASCADE, null=True, blank=True)

    # المستخدم صاحب المنشور
    p_type = models.CharField(max_length=60, choices=POST_TYPE_CHOICES, verbose_name="نوع المنشور")
    title=  models.CharField(max_length=200, verbose_name="عنوان المنشور")
    content = models.TextField(verbose_name="محتوى المنشور")
    likes = models.IntegerField(default=0, verbose_name="الإعجاب")
    dislikes = models.IntegerField(default=0, verbose_name="ديسلايك")
    date_published = models.DateTimeField(auto_now=False) # Schedule Posts
    
    categories = models.ManyToManyField("Category", verbose_name="الأقسام")

    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, allow_unicode=True)

    

    class Meta:
        verbose_name = "منشور"
        verbose_name_plural ="المنشورات"


    def __str__(self):
        return self.title 
    
    def save(self, *args, **kwargs):  
        self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs) 
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="المنشور") 
    ## المستخدم صاحب التعليق
    content = models.TextField(verbose_name="التعليق")
    date_published = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name = 'تعليق'
        verbose_name_plural = "التعليقات"

    def __str__(self):
        return self.content[:10]

class Category(models.Model):
    name= models.CharField(max_length=70) 

    def __str__(self): 
        return self.name
    
    class Meta:
        verbose_name = 'قسم '
        verbose_name_plural = 'الأقسام '

author/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
from django.shortcuts import render

from .models import * 

# Create your views here.
def all(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    } 
    return render(request, 'post/all.html', context)
    

def single_post(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post, 
    }

    return render(request, 'post/single-post.html', context)

post/templates/post/all.html
{% extends 'base.html' %}

{% block title %}جميع المنشورات{% endblock title %}

{% block content %}


<h2>جميع المنشورات</h2>

<div class='row'>
    {% for post in posts  %}
    <div class='col-sm-4 card p-4 m-4'>
        <h4><b>
            <a href='{% url 'post:single-post' post.id %}'>
            {{post}}
            </a>
        </b></h4> 
        <p>{{post.date_published}}</p>
        <br>
        {{post.content|truncatewords:20}}
    </div>
    {% endfor %}
</div>

{% endblock content %}

post/templates/post/single-post.html
{% extends 'base.html' %}

{% block title %}{{post}}{% endblock title %}

{% block content %}

<div class='row'>
    <div class='col-sm-12 card p-4 m-4'>
        <h4><b>
            {{post}}
        </b></h4> 
        <p>{{post.date_published}}</p>
        <br>
        {{post.content}}
    </div>
</div>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <style>
        * {
            font-family: 'Cairo', sans-serif;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">DONE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
    <div class='container'>
          
          {% block content %}
          {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  </body>
</html>